---
- hosts: puppet-node
  gather_facts: false
  pre_tasks:
    - name: Install Python
      raw: bash -c "test -e /usr/bin/python3 || (yum -y update && yum install -y python3) || (flock /var/lib/dpkg/lock-frontend apt -y update && apt install -y python python3)"
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0
      changed_when: result.stdout != ""
    - action: setup
  roles:
    - common
